apiVersion: v1
kind: Service
metadata:
  name: apache-sample-app-service
  namespace: default
  labels:
    app: apache-sample-app
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    app: apache-sample-app
    tier: was
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-sample-app-deploy-cfg
  namespace: default
  labels:
    app: apache-sample-app
data:
  deploy-spec.yaml: |
    spec:
      selector:
        matchLabels:
          app: apache-sample-app
          tier: was
      template:
        metadata:
          labels:
            app: apache-sample-app
            tier: was
        spec:
          imagePullSecrets:
          - name: ''
          containers:
          - ports:
            - containerPort: 8080
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: apache-sample-app-pipeline
  namespace: default
  labels:
    app: apache-sample-app
spec:
  params:
    - name: app-name
      type: string
      description: Application name
    - name: deploy-cfg-name
      description: Configmap name for description
    - name: deploy-env-json
      description: Deployment environment variable in JSON object form
    - name: git-url
      description: Git url
    - name: git-rev
      description: Git revision
    - name: image-url
      description: Image url
  workspaces:
    - name: git-source
      description: The git repo will be cloned onto the volume backing this workspace
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: git-source
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-rev)
    - name: build-source
      taskRef:
        name: s2i
        kind: ClusterTask
      runAfter:
        - git-clone
      workspaces:
        - name: git-source
          workspace: git-source
      params:
        - name: BUILDER_IMAGE
          value: tmaxcloudck/s2i-apache:2.4
        - name: PACKAGE_SERVER_URL
          value: ''
        - name: REGISTRY_SECRET_NAME
          value: ''
        - name: IMAGE_URL
          value: $(params.image-url)
    - name: deploy
      taskRef:
        name: generate-and-deploy-using-kubectl
        kind: ClusterTask
      runAfter:
        - build-source
      params:
        - name: app-name
          value: $(params.app-name)
        - name: image-url
          value: $(tasks.build-source.results.image-url)
        - name: deploy-cfg-name
          value: $(params.deploy-cfg-name)
        - name: deploy-env-json
          value: $(params.deploy-env-json)
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: apache-sample-app-pipeline-run-1
  namespace: default
  labels:
    app: apache-sample-app
spec:
  serviceAccountName: tutorial-service
  pipelineRef:
    name: apache-sample-app-pipeline
  workspaces:
    - name: git-source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: csi-cephfs-sc
          resources:
            requests:
              storage: 500Mi
  params:
    - name: app-name
      value: apache-sample-app
    - name: deploy-cfg-name
      value: apache-sample-app-deploy-cfg
    - name: deploy-env-json
      value: "{'EX':'EXVAL', 'EX2': 'EXVAL2'}"
    - name: git-url
      value: https://github.com/microsoft/project-html-website
    - name: git-rev
      value: master
    - name: image-url
      value: 172.22.11.2:30500/test-apache
