apiVersion: v1
kind: Service
metadata:
  name: apache-sample-app-service
  namespace: default
  labels:
    app: apache-sample-app
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    app: apache-sample-app
    tier: was
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-sample-app-deploy-cfg
  namespace: default
  labels:
    app: apache-sample-app
data:
  deploy-spec.yaml: |
    spec:
      selector:
        matchLabels:
          app: apache-sample-app
          tier: was
      template:
        metadata:
          labels:
            app: apache-sample-app
            tier: was
        spec:
          imagePullSecrets:
          - name: ''
          containers:
          - ports:
            - containerPort: 8080
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: apache-sample-app-input-git
  namespace: default
  labels:
    app: apache-sample-app
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/microsoft/project-html-website
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: apache-sample-app-output-image
  namespace: default
  labels:
    app: apache-sample-app
spec:
  type: image
  params:
    - name: url
      value: 172.22.11.2:30500/test-apache:2333
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: apache-sample-app-pipeline
  namespace: default
  labels:
    app: apache-sample-app
spec:
  resources:
    - name: source-repo
      type: git
    - name: image
      type: image
  params:
    - name: app-name
      type: string
      description: Application name
    - name: deploy-cfg-name
      description: Configmap name for description
    - name: deploy-env-json
      description: Deployment environment variable in JSON object form
  tasks:
    - name: build-source
      taskRef:
        name: s2i-test
        kind: ClusterTask
      params:
        - name: BUILDER_IMAGE
          value: tmaxcloudck/s2i-apache:2.4
        - name: PACKAGE_SERVER_URL
          value: ''
        - name: REGISTRY_SECRET_NAME
          value: ''
      resources:
        inputs:
          - name: source
            resource: source-repo
        outputs:
          - name: image
            resource: image
    - name: scan-and-sign-image
      taskRef:
        name: analyze-image-vulnerabilities
        kind: ClusterTask
      resources:
        inputs:
          - name: scanned-image
            resource: image
            from:
              - build-source
      params:
        - name: image-url
          value: $(tasks.build-source.results.image-url)
    - name: deploy
      taskRef:
        name: generate-and-deploy-using-kubectl-test
        kind: ClusterTask
      runAfter:
        - scan-and-sign-image
      resources:
        inputs:
          - name: image
            resource: image
      params:
        - name: app-name
          value: $(params.app-name)
        - name: image-url
          value: $(tasks.build-source.results.image-url)
        - name: deploy-cfg-name
          value: $(params.deploy-cfg-name)
        - name: deploy-env-json
          value: $(params.deploy-env-json)
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: apache-sample-app-pipeline-run-1
  namespace: default
  labels:
    app: apache-sample-app
spec:
  serviceAccountName: tutorial-service
  pipelineRef:
    name: apache-sample-app-pipeline
  resources:
    - name: source-repo
      resourceRef:
        name: apache-sample-app-input-git
    - name: image
      resourceRef:
        name: apache-sample-app-output-image
  params:
    - name: app-name
      value: apache-sample-app
    - name: deploy-cfg-name
      value: apache-sample-app-deploy-cfg
    - name: deploy-env-json
      value: "{'EX':'EXVAL', 'EX2': 'EXVAL2'}"
